// <auto-generated />
using EngineeringFactory.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EngineeringFactory.Migrations
{
    [DbContext(typeof(EngineeringFactoryContext))]
    [Migration("20190113105735_InitDB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EngineeringFactory.Models.Coefficient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<int>("ProductCode");

                    b.Property<int>("ResourceId");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode");

                    b.HasIndex("ResourceId");

                    b.ToTable("Coefficients");
                });

            modelBuilder.Entity("EngineeringFactory.Models.Forecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DateMonth");

                    b.Property<int>("DateYear");

                    b.Property<int>("Demand");

                    b.Property<int>("ProductCode");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode");

                    b.ToTable("Forecasts");
                });

            modelBuilder.Entity("EngineeringFactory.Models.Product", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Price");

                    b.Property<string>("Title");

                    b.HasKey("Code");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EngineeringFactory.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("EngineeringFactory.Models.Coefficient", b =>
                {
                    b.HasOne("EngineeringFactory.Models.Product", "Product")
                        .WithMany("Coefficients")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EngineeringFactory.Models.Resource", "Resource")
                        .WithMany("Coefficients")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EngineeringFactory.Models.Forecast", b =>
                {
                    b.HasOne("EngineeringFactory.Models.Product", "Product")
                        .WithMany("Forecasts")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
